SUMMARY = "WebKitBrowser plugin"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://../LICENSE;md5=16cf2209d4e903e4d5dcd75089d7dfe2"

PR = "r1"
PV = "3.0+git${SRCPV}"

S = "${WORKDIR}/git/WebKitBrowser"

PROVIDES += "webkitbrowser-plugin"
RPROVIDES_${PN} += "webkitbrowser-plugin"

SRC_URI = "git://github.com/rdkcentral/rdkservices.git;protocol=git;branch=main \
  file://0001-Inject-badger-script-source-for-Pluto.patch;patchdir=../ \
  file://0002-Use-SYSLOG-instead-of-TRACE.patch;patchdir=../ \
  file://0003-Increase-browser-creation-timeout.patch;patchdir=../ \
  file://0004-Reduce-BrowserConsoleLog.patch;patchdir=../ \
  file://0005-Enable-mixed-content.patch;patchdir=../ \
"

# Tip of the main at Apr 28, 2021
SRCREV = "ddd162966bdc7000f6ff6028716b5ba3e2bee9e4"

inherit cmake pkgconfig python3native

TOOLCHAIN = "gcc"

DEPENDS += "wpeframework wpeframework-tools-native ${WPEWEBKIT}"

PACKAGECONFIG ??= "residentapp searchanddiscoveryapp htmlapp lightningapp aampjsbindings badgerbridge"

PACKAGECONFIG[debug]                 = "-DCMAKE_BUILD_TYPE=Debug,-DCMAKE_BUILD_TYPE=Release,"
PACKAGECONFIG[residentapp]           = "-DPLUGIN_WEBKITBROWSER_RESIDENT_APP=ON,-DPLUGIN_WEBKITBROWSER_RESIDENT_APP=OFF,"
PACKAGECONFIG[searchanddiscoveryapp] = "-DPLUGIN_WEBKITBROWSER_SEARCH_AND_DISCOVERY_APP=ON,-DPLUGIN_WEBKITBROWSER_SEARCH_AND_DISCOVERY_APP=OFF,"
PACKAGECONFIG[htmlapp]               = "-DPLUGIN_WEBKITBROWSER_HTML_APP=ON,-DPLUGIN_WEBKITBROWSER_HTML_APP=OFF,"
PACKAGECONFIG[lightningapp]          = "-DPLUGIN_WEBKITBROWSER_LIGHTNING_APP=ON,-DPLUGIN_WEBKITBROWSER_LIGHTNING_APP=OFF,"
PACKAGECONFIG[aampjsbindings]        = "-DPLUGIN_WEBKITBROWSER_AAMP_JSBINDINGS=ON,-DPLUGIN_WEBKITBROWSER_AAMP_JSBINDINGS=OFF,aamp"
PACKAGECONFIG[badgerbridge]          = "-DPLUGIN_WEBKITBROWSER_BADGER_BRIDGE=ON,-DPLUGIN_WEBKITBROWSER_BADGER_BRIDGE=OFF,"

WEBKITBROWSER_AUTOSTART ?= "false"
WEBKITBROWSER_MEDIADISKCACHE ?= "false"
WEBKITBROWSER_MEMORYPRESSURE ?= "databaseprocess:50m,networkprocess:50m,webprocess:200m,rpcprocess:50m"
WEBKITBROWSER_MEMORYPROFILE ?= "192m"
WEBKITBROWSER_MSEBUFFERS ?= "audio:2m,video:15m,text:1m"
WEBKITBROWSER_STARTURL ?= "about:blank"
WEBKITBROWSER_DISKCACHE ?= "10"
WEBKITBROWSER_XHRCACHE ?= "true"
WEBKITBROWSER_TRANSPARENT ?= "true"
WEBKITBROWSER_INJECTEBLE_BUNDLE ?= "libWPEInjectedBundle.so"

#setting 100KB localstorage size
HTML_APP_LOCALSTORAGESIZE ?= "100"
LIGHTNING_APP_LOCALSTORAGESIZE ?= "100"

#setting 5MB localstorage size
SEARCH_AND_DISCOVERY_APP_LOCALSTORAGESIZE ?= "5120"
RESIDENT_APP_LOCALSTORAGESIZE ?= "5120"

RESIDENT_APP_STARTURL ?= "about:blank"
RESIDENT_APP_AUTOSTART ?= "false"
RESIDENT_APP_CLIENTIDENTIFIER ?= "wst-residentapp"
SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER ?= "wst-searchanddiscoveryapp"
WEBKITBROWSER_CLIENTIDENTIFIER ?= "wst-webkitbrowser"
HTML_APP_CLIENTIDENTIFIER ?= "wst-htmlapp"
LIGHTNING_APP_CLIENTIDENTIFIER ?= "wst-lightningapp"
HTML_APP_LOCALSTORAGE ?= "/opt/persistent/rdkservices/HtmlApp"
LIGHTNING_APP_LOCALSTORAGE ?= "/opt/persistent/rdkservices/LightningApp"
SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE ?= "/opt/persistent/rdkservices/SearchAndDiscoveryApp"
RESIDENT_APP_LOCALSTORAGE ?= "/opt/persistent/rdkservices/ResidentApp"
SEARCH_AND_DISCOVERY_APP_DISKCACHEDIR ?= "/tmp/data/.cache"
RESIDENT_APP_DISKCACHEDIR ?= "/tmp/data/.cache"
WEBKITBROWSER_DISKCACHEDIR ?= "/mnt/wpe_cache/wpe"
HTML_APP_DISKCACHEDIR ?= "/tmp/data/.cache/HtmlApp"
LIGHTNING_APP_DISKCACHEDIR ?= "/tmp/data/.cache/LightningApp"

SEARCH_AND_DISCOVERY_APP_SECURE="false"
RESIDENT_APP_SECURE="false"
HTML_APP_SECURE="true"
LIGHTNING_APP_SECURE="true"
WEBKITBROWSER_SECURE="true"

EXTRA_OECMAKE += " \
    -DPYTHON_EXECUTABLE=${STAGING_BINDIR_NATIVE}/python3-native/python3 \
    -DCMAKE_SYSROOT=${STAGING_DIR_HOST} \
    -DBUILD_REFERENCE=${SRCREV} \
    -DBUILD_SHARED_LIBS=ON \
    -DPLUGIN_WEBKITBROWSER=ON \
    -DPLUGIN_WEBKITBROWSER_AUTOSTART="${WEBKITBROWSER_AUTOSTART}" \
    -DPLUGIN_WEBKITBROWSER_MEDIADISKCACHE="${WEBKITBROWSER_MEDIADISKCACHE}" \
    -DPLUGIN_WEBKITBROWSER_MEMORYPRESSURE="${WEBKITBROWSER_MEMORYPRESSURE}" \
    -DPLUGIN_WEBKITBROWSER_MEMORYPROFILE="${WEBKITBROWSER_MEMORYPROFILE}" \
    -DPLUGIN_WEBKITBROWSER_MSEBUFFERS="${WEBKITBROWSER_MSEBUFFERS}" \
    -DPLUGIN_WEBKITBROWSER_STARTURL="${WEBKITBROWSER_STARTURL}" \
    -DPLUGIN_WEBKITBROWSER_DISKCACHE="${WEBKITBROWSER_DISKCACHE}" \
    -DPLUGIN_WEBKITBROWSER_XHRCACHE="${WEBKITBROWSER_XHRCACHE}" \
    -DPLUGIN_WEBKITBROWSER_TRANSPARENT="${WEBKITBROWSER_TRANSPARENT}" \
    -DPLUGIN_WEBKITBROWSER_INJECTEBLE_BUNDLE="${WEBKITBROWSER_INJECTEBLE_BUNDLE}" \
    -DPLUGIN_HTML_APP_LOCALSTORAGESIZE="${HTML_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_LIGHTNING_APP_LOCALSTORAGESIZE="${LIGHTNING_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_LOCALSTORAGESIZE="${SEARCH_AND_DISCOVERY_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_RESIDENT_APP_LOCALSTORAGESIZE="${RESIDENT_APP_LOCALSTORAGESIZE}" \
    -DPLUGIN_WEBKITBROWSER_LOCALSTORAGESIZE="${WEBKITBROWSER_LOCALSTORAGESIZE}" \
    -DPLUGIN_RESIDENT_APP_CLIENTIDENTIFIER="${RESIDENT_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_RESIDENT_APP_AUTOSTART="${RESIDENT_APP_AUTOSTART}" \
    -DPLUGIN_RESIDENT_APP_STARTURL="${RESIDENT_APP_STARTURL}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER="${SEARCH_AND_DISCOVERY_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_WEBKITBROWSER_CLIENTIDENTIFIER="${WEBKITBROWSER_CLIENTIDENTIFIER}" \
    -DPLUGIN_HTML_APP_CLIENTIDENTIFIER="${HTML_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_LIGHTNING_APP_CLIENTIDENTIFIER="${LIGHTNING_APP_CLIENTIDENTIFIER}" \
    -DPLUGIN_HTML_APP_LOCALSTORAGE="${HTML_APP_LOCALSTORAGE}" \
    -DPLUGIN_HTML_APP_COOKIESTORAGE="${HTML_APP_LOCALSTORAGE}" \
    -DPLUGIN_LIGHTNING_APP_LOCALSTORAGE="${LIGHTNING_APP_LOCALSTORAGE}" \
    -DPLUGIN_LIGHTNING_APP_COOKIESTORAGE="${LIGHTNING_APP_LOCALSTORAGE}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE="${SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_COOKIESTORAGE="${SEARCH_AND_DISCOVERY_APP_LOCALSTORAGE}" \
    -DPLUGIN_RESIDENT_APP_LOCALSTORAGE="${RESIDENT_APP_LOCALSTORAGE}" \
    -DPLUGIN_RESIDENT_APP_COOKIESTORAGE="${RESIDENT_APP_LOCALSTORAGE}" \
    -DPLUGIN_WEBKITBROWSER_DISKCACHEDIR="${WEBKITBROWSER_DISKCACHEDIR}" \
    -DPLUGIN_RESIDENT_APP_DISKCACHEDIR="${RESIDENT_APP_DISKCACHEDIR}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_DISKCACHEDIR="${SEARCH_AND_DISCOVERY_APP_DISKCACHEDIR}" \
    -DPLUGIN_LIGHTNING_APP_DISKCACHEDIR="${LIGHTNING_APP_DISKCACHEDIR}" \
    -DPLUGIN_HTML_APP_DISKCACHEDIR="${HTML_APP_DISKCACHEDIR}" \
    -DPLUGIN_SEARCH_AND_DISCOVERY_APP_SECURE="${SEARCH_AND_DISCOVERY_APP_SECURE}" \
    -DPLUGIN_RESIDENT_APP_SECURE="${RESIDENT_APP_SECURE}" \
    -DPLUGIN_HTML_APP_SECURE="${HTML_APP_SECURE}" \
    -DPLUGIN_LIGHTNING_APP_SECURE="${LIGHTNING_APP_SECURE}" \
    -DPLUGIN_WEBKITBROWSER_SECURE="${WEBKITBROWSER_SECURE}" \
"

FILES_SOLIBSDEV = ""
FILES_${PN} += "${libdir}/wpeframework/plugins/*.so ${libdir}/*.so ${datadir}/WPEFramework/*"
FILES_${PN}-dbg += "${datadir}/WPEFramework/WebKitBrowser/.debug"

INSANE_SKIP_${PN} += "libdir staticdev dev-so"
INSANE_SKIP_${PN}-dbg += "libdir"
